### ISSUE TITLE
recommender_system 里中\英版插图内容差异比较大，是否要统一

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/book#148]
![6fcbb902eb8b88c9f7b849f47](https://cloud.githubusercontent.com/assets/1908992/23653718/77f43b86-0368-11e7-80ad-f9694c7d67ae.png)

如上图所示目测两版的差异。

咨询了@luotao1 ,建议是『中文插图是@Zrechel 手绘，英文原版意思不对，英文版应该按照中文手绘图修改』

**Comment by wangkuiyi** [comment]
这里我有点儿担心： 我当时翻译的时候，看中文版里 @Zrachel 的手绘插图的时候其实没有看明白。右边插图是我从yotube recommender system的论文里摘出来的，当时看的时候和论文中的文字是能对上的。

@luotao1 @Zrachel ，当时手绘的时候是因为发现右图有什么问题呢？

**Comment by luotao1** [comment]
1. 因为我们写稿的时候，没有特别详细的写论文。所以现在的图是和现在的文字对应的。
2. 原文中的图，有3个relu，看背景的时候，并不需要了解。

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
