### ISSUE TITLE
文本相关性（二期）

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/book#15]
请先阅读[中文教程撰写统一标准](https://github.com/PaddlePaddle/book/wiki/中文教程撰写统一标准)。

要求：
- 时间节点：暂未定
- 提交地址：[query_relationship目录](https://github.com/PaddlePaddle/book/blob/develop/query_relationship/)。
- 提交方式：分两个PR，先提交可完整运行的demo代码，等review通过后，再撰写中文教程。
- 可参考：[其他demo代码](https://github.com/PaddlePaddle/Paddle/tree/develop/demo/)。

**Comment by Cherishzhang** [comment]
@luotao1  我想认领该任务。

**Comment by Cherishzhang** [comment]
有个疑问想明确一下，该任务的目标是训练模型，完成query-url的排序任务么？

**Comment by Zrachel** [comment]
是的，是根据搜索点击数据训练模型，进行query相关性排序。
比如，可以用http://research.microsoft.com/en-us/um/beijing/projects/letor/letor4download.aspx 数据中Supervised ranking任务的数据。（或者任意learning to rank的数据）

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
