### ISSUE TITLE
NN网络+CRF为什么设置GPU=True报错

### ISSUE THREAD

**Issue by hitwangshuai** [PaddlePaddle/book#353]
![bef2f0f9d1449dd4857824c4076fdd6c](https://user-images.githubusercontent.com/22500910/28743349-5c464f22-747a-11e7-8f90-1cd99905f8b5.png)
hi，您好，麻烦问一下，为什么我网络结构里配置RNN/LSTM+CRF，开启--use_gpu=True报错，设置成false就不报错
在CPU模式下训练NN+CRF的好慢，单纯一层CRF速度倒是还可以

**Comment by Superjomn** [comment]
reference
https://github.com/PaddlePaddle/Paddle/issues/3091

> CRF层目前不支持GPU训练。

**Comment by hitwangshuai** [comment]
请问后续V2版本会升级解决这个问题吗

**Comment by Superjomn** [comment]
现在在做重构，会引入operator，并重写之前的逻辑。 Layer/Op 没有 CPU/GPU 版本不应该直接挂掉，隐含copy这些机制在新版会添加进去。

但那是至少两个月之后了。。

**Comment by hitwangshuai** [comment]
那请问v1版目前是否支持GPU版的NN+CRF加速？

**Comment by Superjomn** [comment]
按上面的结论，不支持？ @qingqing01 
v2 不支持的话， v1是更老的版本，应该也不支持

**Comment by hitwangshuai** [comment]
啊.....现在用CPU的训练超级慢。。。。

**Comment by qingqing01** [comment]
@Superjom @hitwangshuai  v1版本支持设置`paralle_nn`，来支持CPU、GPU混合运算。v2版本相关联的 PaddlePaddle/Paddle#3091 ，因为这个问题出现的较多，我们应该最近fix下v2版本问题，`NN网络+CRF` 支持GPU训练。

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
