### ISSUE TITLE
获取路径失败

### ISSUE THREAD

**Issue by yqxqls** [PaddlePaddle/book#359]
如图
![image](https://user-images.githubusercontent.com/26181201/28947731-1d1e207c-78e4-11e7-8854-e0347bd1a103.png)

是在docker环境下运行paddlepaddle/book的

**Comment by yqxqls** [comment]
为什么没有人回复的？？？

**Comment by Yancey0623** [comment]
@yqxqls 请问用的是哪个版本的Docker image以及运行的哪个demo呢？

**Comment by yqxqls** [comment]
docker.paddlepaddle.org/book

**Comment by Yancey0623** [comment]
看起来是个bug，我测试下提个PR修复这个问题，多谢 @yqxqls ，另外latest镜像我们会随时更新，可以使用docker.paddlepaddle.org/book:0.10.0 这是我们上一个稳定版本。

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
