### ISSUE TITLE
请问图中的label输出5，如何知道分类5是对应哪张图啊?如图

### ISSUE THREAD

**Issue by yanqls** [PaddlePaddle/book#362]
请问图中的label输出5,怎么知道这个分类5是对应哪张图？如图
![image](https://user-images.githubusercontent.com/30828687/29066372-973106c4-7c61-11e7-845f-ca6234321cb7.png)

**Comment by yqxqls** [comment]
为什么没有人回复的？？？

**Comment by yqxqls** [comment]
没有人回复的，都这么多天了~

**Comment by qingqing01** [comment]
不好意思，回复晚了。

>  请问图中的label输出5,怎么知道这个分类5是对应哪张图？如图

预测是路径 `image/dog.png` 这张图片， label 5是dog这一类。

### 如何获取label类别：

下载cifar10数据存储路径为根目录下：  

```
~/.cache/paddle/dataset/cifar/cifar-10-python.tar.gz
```

可以先解压该文件：

```
tar -xf cifar-10-python.tar.gz
```

会看到如下文件：

```
batches.meta data_batch_1 data_batch_2 data_batch_3 data_batch_4 data_batch_5 readme.html  test_batch
```

然后可以通过Python程序读取`batches.meta`查看到具体类别，Python程序如下：

```
import cPickle
with open('batches.meta', 'rb') as fo:
    dict = cPickle.load(fo)
    print dict
```

会打印：

```
{'num_cases_per_batch': 10000, 'label_names': ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck'], 'num_vis': 3072}
```

其中 `label_names`里 `['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']` 对应的整数label值是0,1,2, .., 9。

也可参考数据官网说明：https://www.cs.toronto.edu/~kriz/cifar.html

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
