### ISSUE TITLE
请求为demo添加数据维度说明

### ISSUE THREAD

**Issue by zhuantouer** [PaddlePaddle/book#441]
paddle的官方文档写的不太详细，比如concat是怎么拼接的，按照数据的哪个维度。没有数据维度层面的解释，paddle如同黑盒一般。
如果有详细的数据维度说明，使用者可以很方便、灵活的根据demo构建自己的网络，会对paddle的计算流程和模型设计有清晰的认识，以便编写合乎paddle规范的代码。

辛苦paddle同学补充demo的数据维度说明，
比如https://github.com/PaddlePaddle/book/blob/develop/07.label_semantic_roles/train.py
中的feature_out数据维度是什么（[batch, sen_len, label_cnt]?）

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
