### ISSUE TITLE
建议增加运动姿态识别分类的例子

### ISSUE THREAD

**Issue by realsnake** [PaddlePaddle/book#497]
建议增加基于时间序列的传感器数据的识别运动姿态分类的例子，帮助大家学习使用。
这里有一些相关资料和论文索引 
https://github.com/jindongwang/activityrecognition

**Comment by shanyi15** [comment]
收到，感谢您的建议！

**Comment by NHZlX** [comment]
Multi-Person Pose Estimation，最近我正在训练，训练代码已经可以使用，具体可以参考 https://github.com/NHZlX/paddle_rtpose  ，文档以及前向运行的代码正在完善，后续会加入到paddle  models的repo中，欢迎提issue

**Comment by realsnake** [comment]
@NHZIX 多谢提供参考例子。我看例子里的说明还是基于图片的识别，我这里希望提供的是基于时间序列的传感器数据的例子。

**Comment by NHZlX** [comment]
奥奥，这样，那看来涉及到姿态识别分类的方向有很多，那你可不可以在这个issue下具体描述一下“基于时间序列的传感器数据”或者有关这种姿态识别的资料呢

**Comment by realsnake** [comment]
@NHZlX  已重新编辑issue

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!

**Comment by cernard** [comment]
Hi, 请问基于传感器的运动姿态分类有更多的资源可以推荐吗？
