### ISSUE TITLE
paddlepaddle在mac环境下安装运行遇到2个问题

### ISSUE THREAD

**Issue by DAVINDAI** [PaddlePaddle/book#498]
1.本地安装 提示缺少 _swig_paddle动态库，这个库可以从哪儿获得？
2.docker中安装，图片识别教程需要显示图像时，提示没有tkinter，安装_tkinter后又提示没有DISPLAY，一番研究之后，发现是一个在docker中显示GUI的问题。按照这个文档https://medium.com/@dimitris.kapanidis/running-gui-apps-in-docker-containers-3bd25efa862a 可以在docker中运行firefox，但是我们的paddle教程的例子没有错误提示了，但是没有显示出图像。
先暂停一下，总结梳理后再重新搞。

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
