### ISSUE TITLE
AVX 指令集问题

### ISSUE THREAD

**Issue by memory-overflow** [PaddlePaddle/book#508]
官方提供的 pip 安装方法和 docker 镜像都默认带有 AVX 指令集，有没有不带默认 AVX 指令集的镜像呢？源码编译一次需要好长时间。

**Comment by typhoonzero** [comment]
您好，目前暂时不提供无AVX版本的二进制或镜像。需要自行编译。

**Comment by luotao1** [comment]
- pip安装时，可以参考如下表格中的`cpu_noavx_openblas`
http://www.paddlepaddle.org/docs/develop/documentation/fluid/zh/build_and_install/pip_install_cn.html#id14
- docker镜像，可以访问https://hub.docker.com/r/paddlepaddle/paddle/tags/ ，有latest-noavx-openblas 版本。

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
