### ISSUE TITLE
08. 机器翻译 的 infer.py 会 crash

### ISSUE THREAD

**Issue by daming-lu** [PaddlePaddle/book#557]
训练没问题，但是会 run 很久，所以没有等 run 完
![screen shot 2018-06-22 at 6 52 21 pm](https://user-images.githubusercontent.com/5635322/41804646-44d55996-764f-11e8-84dc-8b8531c945b7.png)

infer.py 会 crash
![screen shot 2018-06-22 at 6 52 40 pm](https://user-images.githubusercontent.com/5635322/41804648-48488256-764f-11e8-94f3-991285f5e445.png)

我记得 infer 是不会用到 train 的结果的，那不知道为啥会crash。如果需要用到训练完的model，如果不大的话，能否提供在github里？这样能确保 infer 不 crash

**Comment by luotao1** [comment]
最好使用训练好的model，不然infer出来的结果没法看。V2是使用了训练好的model，也提供了下载地址。

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. we will close it today for the sake of other user’s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
